lr: 0.0001
lr_scheduler_flag: MultistepLR
model_kwargs:
  dropout: 0.2
  embed_dim: 256
  hidden_dim: 512
  num_channels: 6
  num_classes: 43
  num_heads: 8
  num_layers: 2
  num_mlp_layers: 3
  num_patches: 256
  patch_size: 8
